analysis/codelists.py, codelists/codelists.json, codelists/codelists.txt, codelists/user-KatieDavies_1234-f2f-consultation.csv, codelists/user-KatieDavies_1234-virtual-consultation.csv
This adds the two codelists that are still in development for this study, one that contains f2f and one that contains virtual consultations.
=> Add codelists for study

analysis/dataset_definition.py
I have added ethnicity group names to the study definition.
=> add-ethnicity-group-names

analysis/dataset_definition.py, analysis/summarise_consultation_dataset.R, analysis/visualise_consultation_dataset.R, project.yaml
In this example I first summarise the dataset and then create a simple figure to visualise the summarised data.
=> Create visualisation consultations

analysis/dataset_definition.py, analysis/investigate_consultation_codes.R, analysis/summarise_consultation_dataset.R, analysis/visualise_consultation_dataset.R, project.yaml
This also uses another way to specify paths using the here package in R scripts.
=> Improve folder structure of output files

analysis/dataset_definition.py, analysis/investigate_consultation_codes.R, analysis/summarise_consultation_dataset.R, analysis/visualise_consultation_dataset.R, project.yaml
This follows current OpenSAFELY guidelines for primary and secondary disclosure control, see https://docs.opensafely.org/releasing-files/#1-applying-disclosure-controls-to-outputs-you-request-for-release.
=> Add disclosure controls

analysis/dataset_definition.py, analysis/investigate_consultation_codes.R, analysis/summarise_consultation_dataset.R, analysis/visualise_consultation_dataset.R, project.yaml
This adds two parameters (start_date, end_date). This commit only replicates the behaviour of the original study but allows us to add more study time frames simply by adding another action with different parameters.
=> Parameterise dataset definition

analysis/dataset_definition.py, analysis/investigate_consultation_codes.R, analysis/summarise_consultation_dataset.R, analysis/visualise_consultation_dataset.R, project.yaml
This allows us to differetiate between the total number of all consultations (`n_sum`) and whether or not a patient had a consultation (`n_has`).
=> Caculate count of patients who had f2f/virtual consultation 

analysis/investigate_consultation_codes.R, analysis/visualise_consultation_dataset.R
This PR adds descriptions for clinical codes and calculates the percentage of each code within the two consultation types. There are also small aesthetic improvments to the visualisation of the consultation count data.
=> Improve analysis scripts

analysis/dataset_definition.py, analysis/summarise_consultation_dataset.R, analysis/visualise_consultation_dataset.R, project.yaml
I have created more dates representing three months of pre and post pandemic by modifying the project.yaml file. This is important to see the trend/changes in the data using monthly counts.
=> add 6 months data

analysis/measures_definition.py
The second measure script had error of appointment as both numerator and denominator which I have now corrected. The numerator is now virtual consultation.
=> corrected the second measure script

analysis/dataset_definition.py, analysis/measures_definition.py, project.yaml
The behaviour of the code does not change, just making all the updates needed to switch to version 1.
=> Update ehrql to version 1

analysis/measures_definition.py
This is to add one more measure to the definition file which is grouped by age only so we can see total ratio by age.
=> Add measure grouped by age only

analysis/binary_regression.R, project.yaml
This commits adds binary regression  models for the preliminary regression of independent variables (age, sex, ethnicity and imd_quintile) on the outcome variable (has_virtual_consultation). This is meant to see the role of the variables on virtual consultation attendance.
=> add binary regression

analysis/binary_regression.R, project.yaml
This separates the outputs for the regression model corresponding to the three dataset years in the project (2019/20, 2020/21 and 2021/22).
=> add three outputs for the regression model

analysis/dataset_definition.py, analysis/investigate_appointment_status.R, analysis/measures_definition.py, project.yaml
Summarise the last appointment status for all seen appointments.
Closes #53
=> Add appointment status summary

analysis/dataset_definition.py, analysis/measures_definition.py
This is an important addition for the measures that use count_appointment as the denominator. These measures now also only include patients with a registration and an age of 18 or above. The other measures that use count_appointment as the numerator will stay the same as both of these conditions also appear in their denominators.
Closes #56
=> Count appointments in measures only when registered and aged >= 18

analysis/binary_regression.R
This is to capture only the exponentiated output of the regression models and the p-values.
=> Update to regression file

analysis/tidy_consultation_measures.R, project.yaml
The subsequent analyses will only group by female/male so this removes all other sex categories.
=> Remove unused sex categories

analysis/logit_regression.R, analysis/summarise_consultation_dataset.R, project.yaml
This model is meant to examine the effect of independent variables on rate of virtual consultation of the individual-level data.
=> Abodunrin/Add logit_regression model 

analysis/logit_regression.R, project.yaml
This is to run only interaction model using the patient data to investigate variation in rate of remote consultation across the periods 2019, 2020 and 2021.
=> Add interaction model

analysis/logit_regression.R, project.yaml
This combines the logit model without interaction and the interaction models into a single output.
=> Add combined models
